#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : jdk-maven-plugin-testing
Version  : 3.3.0
Release  : 2
URL      : http://repo1.maven.org/maven2/org/apache/maven/plugin-testing/maven-plugin-testing/3.3.0/maven-plugin-testing-3.3.0-source-release.zip
Source0  : http://repo1.maven.org/maven2/org/apache/maven/plugin-testing/maven-plugin-testing/3.3.0/maven-plugin-testing-3.3.0-source-release.zip
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0
Requires: jdk-maven-plugin-testing-data
BuildRequires : apache-maven
BuildRequires : apache-maven2
BuildRequires : javapackages-tools
BuildRequires : jdk-aether
BuildRequires : jdk-aopalliance
BuildRequires : jdk-apache-parent
BuildRequires : jdk-apache-resource-bundles
BuildRequires : jdk-atinject
BuildRequires : jdk-cdi-api
BuildRequires : jdk-cglib
BuildRequires : jdk-commons-cli
BuildRequires : jdk-commons-codec
BuildRequires : jdk-commons-collections
BuildRequires : jdk-commons-compress
BuildRequires : jdk-commons-io
BuildRequires : jdk-commons-lang
BuildRequires : jdk-commons-lang3
BuildRequires : jdk-commons-logging
BuildRequires : jdk-commons-parent
BuildRequires : jdk-doxia
BuildRequires : jdk-doxia-integration-tools
BuildRequires : jdk-doxia-sitetools
BuildRequires : jdk-easymock3
BuildRequires : jdk-glassfish-servlet-api
BuildRequires : jdk-guava
BuildRequires : jdk-guice
BuildRequires : jdk-hamcrest
BuildRequires : jdk-httpcomponents-client
BuildRequires : jdk-httpcomponents-core
BuildRequires : jdk-jdom
BuildRequires : jdk-jsoup
BuildRequires : jdk-jsr-305
BuildRequires : jdk-junit4
BuildRequires : jdk-log4j
BuildRequires : jdk-maven-archiver
BuildRequires : jdk-maven-artifact-resolver
BuildRequires : jdk-maven-common-artifact-filters
BuildRequires : jdk-maven-compiler-plugin
BuildRequires : jdk-maven-filtering
BuildRequires : jdk-maven-invoker
BuildRequires : jdk-maven-jar-plugin
BuildRequires : jdk-maven-javadoc-plugin
BuildRequires : jdk-maven-parent
BuildRequires : jdk-maven-plugin-tools
BuildRequires : jdk-maven-remote-resources-plugin
BuildRequires : jdk-maven-reporting-api
BuildRequires : jdk-maven-reporting-exec
BuildRequires : jdk-maven-resources-plugin
BuildRequires : jdk-maven-shared-incremental
BuildRequires : jdk-maven-shared-utils
BuildRequires : jdk-maven-site-plugin
BuildRequires : jdk-maven-source-plugin
BuildRequires : jdk-objectweb-asm
BuildRequires : jdk-objenesis
BuildRequires : jdk-parboiled
BuildRequires : jdk-pegdown
BuildRequires : jdk-plexus-archiver
BuildRequires : jdk-plexus-build-api
BuildRequires : jdk-plexus-cipher
BuildRequires : jdk-plexus-classworlds
BuildRequires : jdk-plexus-cli
BuildRequires : jdk-plexus-compiler
BuildRequires : jdk-plexus-containers
BuildRequires : jdk-plexus-i18n
BuildRequires : jdk-plexus-interactivity
BuildRequires : jdk-plexus-interpolation
BuildRequires : jdk-plexus-io
BuildRequires : jdk-plexus-resources
BuildRequires : jdk-plexus-sec-dispatcher
BuildRequires : jdk-plexus-utils
BuildRequires : jdk-plexus-velocity
BuildRequires : jdk-qdox
BuildRequires : jdk-sisu
BuildRequires : jdk-slf4j
BuildRequires : jdk-snappy
BuildRequires : jdk-surefire
BuildRequires : jdk-velocity
BuildRequires : jdk-wagon
BuildRequires : jdk-xbean
BuildRequires : jdk-xmlunit
BuildRequires : jdk-xz
BuildRequires : lxml
BuildRequires : openjdk-dev
BuildRequires : python3
BuildRequires : six
BuildRequires : xmvn
Patch1: 0001-Port-to-plexus-utils-3.0.21.patch
Patch2: 0002-Port-to-current-maven-artifact.patch

%description
No detailed description available

%package data
Summary: data components for the jdk-maven-plugin-testing package.
Group: Data

%description data
data components for the jdk-maven-plugin-testing package.


%prep
%setup -q -n maven-plugin-testing-3.3.0
%patch1 -p1
%patch2 -p1

python3 /usr/share/java-utils/pom_editor.py pom_remove_plugin  :maven-enforcer-plugin
sed -i -e "s/MockControl/IMocksControl/g" maven-test-tools/src/main/java/org/apache/maven/shared/tools/easymock/MockManager.java
rm maven-plugin-testing-tools/src/test/java/org/apache/maven/shared/test/plugin/ProjectToolTest.java
python3 /usr/share/java-utils/mvn_alias.py : org.apache.maven.shared:

%build
python3 /usr/share/java-utils/mvn_build.py -s

%install
xmvn-install  -R .xmvn-reactor -n maven-plugin-testing -d %{buildroot}

%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/maven-plugin-testing/maven-plugin-testing-harness.jar
/usr/share/java/maven-plugin-testing/maven-plugin-testing-tools.jar
/usr/share/java/maven-plugin-testing/maven-test-tools.jar
/usr/share/maven-metadata/maven-plugin-testing-maven-plugin-testing-harness.xml
/usr/share/maven-metadata/maven-plugin-testing-maven-plugin-testing-tools.xml
/usr/share/maven-metadata/maven-plugin-testing-maven-plugin-testing.xml
/usr/share/maven-metadata/maven-plugin-testing-maven-test-tools.xml
/usr/share/maven-poms/maven-plugin-testing/maven-plugin-testing-harness.pom
/usr/share/maven-poms/maven-plugin-testing/maven-plugin-testing-tools.pom
/usr/share/maven-poms/maven-plugin-testing/maven-plugin-testing.pom
/usr/share/maven-poms/maven-plugin-testing/maven-test-tools.pom
